# Generated by Django 4.2.5 on 2023-09-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_name_products_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='likes',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
